import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import styles from "./layout.module.css";
import TanstackProvider from "@/components/TanstackProvider/TanstackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NoteHub App | Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.layout}>
          <TanstackProvider>
            <Header />
            {children}
            <Footer />
            <div id="modal-root"></div>
          </TanstackProvider>
        </div>
      </body>
    </html>
  );
}

// app/page.tsx >>>> localhost:3000/ >>>> HomePage() >>> html >>>> browser
// localhost:3000/profile >>> app/profile/page.tsx > ProfilePage() >>>> browser
//localhost:3000/about >>> app/about/page.tsx
