import type { Metadata } from "next";
import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import styles from "./layout.module.css";

import TanstackProvider from "@/components/TanstackProvider/TanstackProvider";
import clsx from "clsx";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
// import clsx from "clsx";

const montserrat = Montserrat({
  weight: ["400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-montserrat",
});

const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  weight: ["300", "400", "500", "600"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: {
    template: "BC-76 | %s",
    default: "BC-76 | My Super App",
  },
  description: "Generated by GoIT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // AUTH PROVIDER
  return (
    <html lang="en">
      <body className={clsx(montserrat.variable, roboto.variable)}>
        <AuthProvider>
          <TanstackProvider>
            <div className={styles.layout}>
              <Header />
              <main>{children}</main>
              <Footer />
            </div>
          </TanstackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
